/**
 * Local campaign photo manifest — paths under public/campaigns/.
 * Auto-generated by scripts/download-campaign-images.mjs
 * Re-run: npm run campaigns:images
 */

export type CampaignImageCategory =
  | "evangelism"
  | "missions"
  | "social"
  | "construction"
  | "reform"
  | "events"
  | "youth"
  | "music"
  | "children"
  | "women"
  | "men"
  | "prayer"
  | "bible"
  | "vehicles"
  | "emergency"
  | "general";

export const CAMPAIGN_IMAGE_MANIFEST: Record<CampaignImageCategory, readonly string[]> = {
  "evangelism": [
    "/campaigns/evangelism/evangelism-01.jpg",
    "/campaigns/evangelism/evangelism-02.jpg",
    "/campaigns/evangelism/evangelism-03.jpg",
    "/campaigns/evangelism/evangelism-04.jpg",
    "/campaigns/evangelism/evangelism-05.jpg",
    "/campaigns/evangelism/evangelism-06.jpg",
    "/campaigns/evangelism/evangelism-07.jpg",
    "/campaigns/evangelism/evangelism-08.jpg",
    "/campaigns/evangelism/evangelism-09.jpg",
    "/campaigns/evangelism/evangelism-10.jpg",
    "/campaigns/evangelism/evangelism-11.jpg",
    "/campaigns/evangelism/evangelism-12.jpg",
    "/campaigns/evangelism/evangelism-13.jpg",
    "/campaigns/evangelism/evangelism-14.jpg",
    "/campaigns/evangelism/evangelism-15.jpg"
  ],
  "missions": [
    "/campaigns/missions/missions-01.jpg",
    "/campaigns/missions/missions-02.jpg",
    "/campaigns/missions/missions-03.jpg",
    "/campaigns/missions/missions-04.jpg",
    "/campaigns/missions/missions-05.jpg",
    "/campaigns/missions/missions-06.jpg",
    "/campaigns/missions/missions-07.jpg",
    "/campaigns/missions/missions-08.jpg",
    "/campaigns/missions/missions-09.jpg",
    "/campaigns/missions/missions-10.jpg",
    "/campaigns/missions/missions-11.jpg",
    "/campaigns/missions/missions-12.jpg",
    "/campaigns/missions/missions-13.jpg",
    "/campaigns/missions/missions-14.jpg",
    "/campaigns/missions/missions-15.jpg"
  ],
  "social": [
    "/campaigns/social/social-01.jpg",
    "/campaigns/social/social-02.jpg",
    "/campaigns/social/social-03.jpg",
    "/campaigns/social/social-04.jpg",
    "/campaigns/social/social-05.jpg",
    "/campaigns/social/social-06.jpg",
    "/campaigns/social/social-07.jpg",
    "/campaigns/social/social-08.jpg",
    "/campaigns/social/social-09.jpg",
    "/campaigns/social/social-10.jpg",
    "/campaigns/social/social-11.jpg",
    "/campaigns/social/social-12.jpg",
    "/campaigns/social/social-13.jpg",
    "/campaigns/social/social-14.jpg",
    "/campaigns/social/social-15.jpg"
  ],
  "construction": [
    "/campaigns/construction/construction-01.jpg",
    "/campaigns/construction/construction-02.jpg",
    "/campaigns/construction/construction-03.jpg",
    "/campaigns/construction/construction-04.jpg",
    "/campaigns/construction/construction-05.jpg",
    "/campaigns/construction/construction-06.jpg",
    "/campaigns/construction/construction-07.jpg",
    "/campaigns/construction/construction-08.jpg",
    "/campaigns/construction/construction-09.jpg",
    "/campaigns/construction/construction-10.jpg",
    "/campaigns/construction/construction-11.jpg",
    "/campaigns/construction/construction-12.jpg",
    "/campaigns/construction/construction-13.jpg",
    "/campaigns/construction/construction-14.jpg",
    "/campaigns/construction/construction-15.jpg"
  ],
  "reform": [
    "/campaigns/reform/reform-01.jpg",
    "/campaigns/reform/reform-02.jpg",
    "/campaigns/reform/reform-03.jpg",
    "/campaigns/reform/reform-04.jpg",
    "/campaigns/reform/reform-05.jpg",
    "/campaigns/reform/reform-06.jpg",
    "/campaigns/reform/reform-07.jpg",
    "/campaigns/reform/reform-08.jpg",
    "/campaigns/reform/reform-09.jpg",
    "/campaigns/reform/reform-10.jpg",
    "/campaigns/reform/reform-11.jpg",
    "/campaigns/reform/reform-12.jpg",
    "/campaigns/reform/reform-13.jpg",
    "/campaigns/reform/reform-14.jpg",
    "/campaigns/reform/reform-15.jpg"
  ],
  "events": [
    "/campaigns/events/events-01.jpg",
    "/campaigns/events/events-02.jpg",
    "/campaigns/events/events-03.jpg",
    "/campaigns/events/events-04.jpg",
    "/campaigns/events/events-05.jpg",
    "/campaigns/events/events-06.jpg",
    "/campaigns/events/events-07.jpg",
    "/campaigns/events/events-08.jpg",
    "/campaigns/events/events-09.jpg",
    "/campaigns/events/events-10.jpg",
    "/campaigns/events/events-11.jpg",
    "/campaigns/events/events-12.jpg",
    "/campaigns/events/events-13.jpg",
    "/campaigns/events/events-14.jpg",
    "/campaigns/events/events-15.jpg"
  ],
  "youth": [
    "/campaigns/youth/youth-01.jpg",
    "/campaigns/youth/youth-02.jpg",
    "/campaigns/youth/youth-03.jpg",
    "/campaigns/youth/youth-04.jpg",
    "/campaigns/youth/youth-05.jpg",
    "/campaigns/youth/youth-06.jpg",
    "/campaigns/youth/youth-07.jpg",
    "/campaigns/youth/youth-08.jpg",
    "/campaigns/youth/youth-09.jpg",
    "/campaigns/youth/youth-10.jpg",
    "/campaigns/youth/youth-11.jpg",
    "/campaigns/youth/youth-12.jpg",
    "/campaigns/youth/youth-13.jpg",
    "/campaigns/youth/youth-14.jpg",
    "/campaigns/youth/youth-15.jpg"
  ],
  "music": [
    "/campaigns/music/music-01.jpg",
    "/campaigns/music/music-02.jpg",
    "/campaigns/music/music-03.jpg",
    "/campaigns/music/music-04.jpg",
    "/campaigns/music/music-05.jpg",
    "/campaigns/music/music-06.jpg",
    "/campaigns/music/music-07.jpg",
    "/campaigns/music/music-08.jpg",
    "/campaigns/music/music-09.jpg",
    "/campaigns/music/music-10.jpg",
    "/campaigns/music/music-11.jpg",
    "/campaigns/music/music-12.jpg",
    "/campaigns/music/music-13.jpg",
    "/campaigns/music/music-14.jpg",
    "/campaigns/music/music-15.jpg"
  ],
  "children": [
    "/campaigns/children/children-01.jpg",
    "/campaigns/children/children-02.jpg",
    "/campaigns/children/children-03.jpg",
    "/campaigns/children/children-04.jpg",
    "/campaigns/children/children-05.jpg",
    "/campaigns/children/children-06.jpg",
    "/campaigns/children/children-07.jpg",
    "/campaigns/children/children-08.jpg",
    "/campaigns/children/children-09.jpg",
    "/campaigns/children/children-10.jpg",
    "/campaigns/children/children-11.jpg",
    "/campaigns/children/children-12.jpg",
    "/campaigns/children/children-13.jpg",
    "/campaigns/children/children-14.jpg",
    "/campaigns/children/children-15.jpg"
  ],
  "women": [
    "/campaigns/women/women-01.jpg",
    "/campaigns/women/women-02.jpg",
    "/campaigns/women/women-03.jpg",
    "/campaigns/women/women-04.jpg",
    "/campaigns/women/women-05.jpg",
    "/campaigns/women/women-06.jpg",
    "/campaigns/women/women-07.jpg",
    "/campaigns/women/women-08.jpg",
    "/campaigns/women/women-09.jpg",
    "/campaigns/women/women-10.jpg",
    "/campaigns/women/women-11.jpg",
    "/campaigns/women/women-12.jpg",
    "/campaigns/women/women-13.jpg",
    "/campaigns/women/women-14.jpg",
    "/campaigns/women/women-15.jpg"
  ],
  "men": [
    "/campaigns/men/men-01.jpg",
    "/campaigns/men/men-02.jpg",
    "/campaigns/men/men-03.jpg",
    "/campaigns/men/men-04.jpg",
    "/campaigns/men/men-05.jpg",
    "/campaigns/men/men-06.jpg",
    "/campaigns/men/men-07.jpg",
    "/campaigns/men/men-08.jpg",
    "/campaigns/men/men-09.jpg",
    "/campaigns/men/men-10.jpg",
    "/campaigns/men/men-11.jpg",
    "/campaigns/men/men-12.jpg",
    "/campaigns/men/men-13.jpg",
    "/campaigns/men/men-14.jpg",
    "/campaigns/men/men-15.jpg"
  ],
  "prayer": [
    "/campaigns/prayer/prayer-01.jpg",
    "/campaigns/prayer/prayer-02.jpg",
    "/campaigns/prayer/prayer-03.jpg",
    "/campaigns/prayer/prayer-04.jpg",
    "/campaigns/prayer/prayer-05.jpg",
    "/campaigns/prayer/prayer-06.jpg",
    "/campaigns/prayer/prayer-07.jpg",
    "/campaigns/prayer/prayer-08.jpg",
    "/campaigns/prayer/prayer-09.jpg",
    "/campaigns/prayer/prayer-10.jpg",
    "/campaigns/prayer/prayer-11.jpg",
    "/campaigns/prayer/prayer-12.jpg",
    "/campaigns/prayer/prayer-13.jpg",
    "/campaigns/prayer/prayer-14.jpg",
    "/campaigns/prayer/prayer-15.jpg"
  ],
  "bible": [
    "/campaigns/bible/bible-01.jpg",
    "/campaigns/bible/bible-02.jpg",
    "/campaigns/bible/bible-03.jpg",
    "/campaigns/bible/bible-04.jpg",
    "/campaigns/bible/bible-05.jpg",
    "/campaigns/bible/bible-06.jpg",
    "/campaigns/bible/bible-07.jpg",
    "/campaigns/bible/bible-08.jpg",
    "/campaigns/bible/bible-09.jpg",
    "/campaigns/bible/bible-10.jpg",
    "/campaigns/bible/bible-11.jpg",
    "/campaigns/bible/bible-12.jpg",
    "/campaigns/bible/bible-13.jpg",
    "/campaigns/bible/bible-14.jpg",
    "/campaigns/bible/bible-15.jpg"
  ],
  "vehicles": [
    "/campaigns/vehicles/vehicles-01.jpg",
    "/campaigns/vehicles/vehicles-02.jpg",
    "/campaigns/vehicles/vehicles-03.jpg",
    "/campaigns/vehicles/vehicles-04.jpg",
    "/campaigns/vehicles/vehicles-05.jpg",
    "/campaigns/vehicles/vehicles-06.jpg",
    "/campaigns/vehicles/vehicles-07.jpg",
    "/campaigns/vehicles/vehicles-08.jpg",
    "/campaigns/vehicles/vehicles-09.jpg",
    "/campaigns/vehicles/vehicles-10.jpg",
    "/campaigns/vehicles/vehicles-11.jpg",
    "/campaigns/vehicles/vehicles-12.jpg",
    "/campaigns/vehicles/vehicles-13.jpg",
    "/campaigns/vehicles/vehicles-14.jpg",
    "/campaigns/vehicles/vehicles-15.jpg"
  ],
  "emergency": [
    "/campaigns/emergency/emergency-01.jpg",
    "/campaigns/emergency/emergency-02.jpg",
    "/campaigns/emergency/emergency-03.jpg",
    "/campaigns/emergency/emergency-04.jpg",
    "/campaigns/emergency/emergency-05.jpg",
    "/campaigns/emergency/emergency-06.jpg",
    "/campaigns/emergency/emergency-07.jpg",
    "/campaigns/emergency/emergency-08.jpg",
    "/campaigns/emergency/emergency-09.jpg",
    "/campaigns/emergency/emergency-10.jpg",
    "/campaigns/emergency/emergency-11.jpg",
    "/campaigns/emergency/emergency-12.jpg",
    "/campaigns/emergency/emergency-13.jpg",
    "/campaigns/emergency/emergency-14.jpg",
    "/campaigns/emergency/emergency-15.jpg"
  ],
  "general": [
    "/campaigns/general/general-01.jpg",
    "/campaigns/general/general-02.jpg",
    "/campaigns/general/general-03.jpg",
    "/campaigns/general/general-04.jpg",
    "/campaigns/general/general-05.jpg",
    "/campaigns/general/general-06.jpg",
    "/campaigns/general/general-07.jpg",
    "/campaigns/general/general-08.jpg",
    "/campaigns/general/general-09.jpg",
    "/campaigns/general/general-10.jpg",
    "/campaigns/general/general-11.jpg",
    "/campaigns/general/general-12.jpg",
    "/campaigns/general/general-13.jpg",
    "/campaigns/general/general-14.jpg",
    "/campaigns/general/general-15.jpg"
  ]
} as const;
