import { createContext, useContext, useState, ReactNode } from "react";

type Lang = "pt" | "en" | "es";

const translations: Record<string, Record<Lang, string>> = {
  // Layout / Common
  "Bem-vindo de volta": { pt: "Bem-vindo de volta", en: "Welcome back", es: "Bienvenido de vuelta" },
  "Recolher": { pt: "Recolher", en: "Collapse", es: "Contraer" },
  "Configurações": { pt: "Configurações", en: "Settings", es: "Configuración" },
  "Sair": { pt: "Sair", en: "Sign out", es: "Salir" },
  "Cancelar": { pt: "Cancelar", en: "Cancel", es: "Cancelar" },
  "Salvar": { pt: "Salvar", en: "Save", es: "Guardar" },
  "Carregando...": { pt: "Carregando...", en: "Loading...", es: "Cargando..." },
  "Erro": { pt: "Erro", en: "Error", es: "Error" },
  "Todos": { pt: "Todos", en: "All", es: "Todos" },
  "Remover": { pt: "Remover", en: "Remove", es: "Eliminar" },
  "Publicar": { pt: "Publicar", en: "Publish", es: "Publicar" },
  "Buscar...": { pt: "Buscar...", en: "Search...", es: "Buscar..." },
  "Exportar": { pt: "Exportar", en: "Export", es: "Exportar" },
  "ou": { pt: "ou", en: "or", es: "o" },

  // Nav
  "Dashboard": { pt: "Dashboard", en: "Dashboard", es: "Panel" },
  "Financeiro": { pt: "Financeiro", en: "Finances", es: "Finanzas" },
  "Membros": { pt: "Membros", en: "Members", es: "Miembros" },
  "Agenda": { pt: "Agenda", en: "Calendar", es: "Agenda" },
  "Bíblia Sagrada": { pt: "Bíblia Sagrada", en: "Holy Bible", es: "Santa Biblia" },
  "Pedidos de Oração": { pt: "Pedidos de Oração", en: "Prayer Requests", es: "Peticiones de Oración" },
  "Comunicação": { pt: "Comunicação", en: "Communication", es: "Comunicación" },
  "Pequenos Grupos": { pt: "Pequenos Grupos", en: "Small Groups", es: "Grupos Pequeños" },
  "Documentos": { pt: "Documentos", en: "Documents", es: "Documentos" },
  "Relatórios": { pt: "Relatórios", en: "Reports", es: "Informes" },
  "Escalas": { pt: "Escalas", en: "Schedules", es: "Escalas" },
  "Gerenciar Acessos": { pt: "Gerenciar Acessos", en: "Manage Access", es: "Gestionar Accesos" },

  // Mobile nav
  "Início": { pt: "Início", en: "Home", es: "Inicio" },
  "Finanças": { pt: "Finanças", en: "Finances", es: "Finanzas" },
  "Bíblia": { pt: "Bíblia", en: "Bible", es: "Biblia" },
  "Perfil": { pt: "Perfil", en: "Profile", es: "Perfil" },

  // Dashboard
  "Visão geral da administração": { pt: "Visão geral da administração", en: "Administration overview", es: "Visión general" },
  "Painel Consolidado da Matriz": { pt: "Painel Consolidado da Matriz", en: "Headquarters Consolidated Panel", es: "Panel Consolidado de la Matriz" },
  "unidades": { pt: "unidades", en: "units", es: "unidades" },
  "Total Membros": { pt: "Total Membros", en: "Total Members", es: "Total Miembros" },
  "Saldo Geral": { pt: "Saldo Geral", en: "Overall Balance", es: "Saldo General" },
  "Detalhamento por Congregação": { pt: "Detalhamento por Congregação", en: "Breakdown by Congregation", es: "Desglose por Congregación" },
  "Gerenciar": { pt: "Gerenciar", en: "Manage", es: "Gestionar" },
  "Congregação": { pt: "Congregação", en: "Congregation", es: "Congregación" },
  "Receita": { pt: "Receita", en: "Revenue", es: "Ingresos" },
  "Despesa": { pt: "Despesa", en: "Expense", es: "Gasto" },
  "Saldo": { pt: "Saldo", en: "Balance", es: "Saldo" },
  "Eventos": { pt: "Eventos", en: "Events", es: "Eventos" },
  "Orações": { pt: "Orações", en: "Prayers", es: "Oraciones" },

  // Super Admin
  "Super Admin": { pt: "Super Admin", en: "Super Admin", es: "Super Admin" },
  "Painel da Plataforma": { pt: "Painel da Plataforma", en: "Platform Panel", es: "Panel de la Plataforma" },
  "Gestão global — visível apenas para você": { pt: "Gestão global — visível apenas para você", en: "Global management — visible only to you", es: "Gestión global — visible solo para usted" },
  "Total de Igrejas": { pt: "Total de Igrejas", en: "Total Churches", es: "Total de Iglesias" },
  "Usuários na Plataforma": { pt: "Usuários na Plataforma", en: "Platform Users", es: "Usuarios en la Plataforma" },
  "Avisos Ativos": { pt: "Avisos Ativos", en: "Active Notices", es: "Avisos Activos" },
  "Todas as Igrejas": { pt: "Todas as Igrejas", en: "All Churches", es: "Todas las Iglesias" },
  "Dados agregados — sem acesso a dados individuais": { pt: "Dados agregados — sem acesso a dados individuais", en: "Aggregated data — no access to individual data", es: "Datos agregados — sin acceso a datos individuales" },
  "Sem cidade": { pt: "Sem cidade", en: "No city", es: "Sin ciudad" },
  "usuários": { pt: "usuários", en: "users", es: "usuarios" },
  "Nenhuma igreja cadastrada": { pt: "Nenhuma igreja cadastrada", en: "No churches registered", es: "Ninguna iglesia registrada" },
  "Avisos da Plataforma": { pt: "Avisos da Plataforma", en: "Platform Notices", es: "Avisos de la Plataforma" },
  "Novo Aviso": { pt: "Novo Aviso", en: "New Notice", es: "Nuevo Aviso" },
  "Título do aviso": { pt: "Título do aviso", en: "Notice title", es: "Título del aviso" },
  "Conteúdo do aviso": { pt: "Conteúdo do aviso", en: "Notice content", es: "Contenido del aviso" },
  "Desativar": { pt: "Desativar", en: "Deactivate", es: "Desactivar" },
  "Ativar": { pt: "Ativar", en: "Activate", es: "Activar" },
  "Nenhum aviso criado": { pt: "Nenhum aviso criado", en: "No notices created", es: "Ningún aviso creado" },
  "Erro ao criar aviso": { pt: "Erro ao criar aviso", en: "Error creating notice", es: "Error al crear aviso" },
  "Aviso criado com sucesso": { pt: "Aviso criado com sucesso", en: "Notice created successfully", es: "Aviso creado con éxito" },
  "Aviso removido": { pt: "Aviso removido", en: "Notice removed", es: "Aviso eliminado" },
  "Acesso negado": { pt: "Acesso negado", en: "Access denied", es: "Acceso denegado" },
  "Sair da conta": { pt: "Sair da conta", en: "Sign out", es: "Cerrar sesión" },
  "Tem certeza que deseja sair? Você precisará fazer login novamente.": { pt: "Tem certeza que deseja sair? Você precisará fazer login novamente.", en: "Are you sure you want to sign out? You'll need to log in again.", es: "¿Está seguro de que desea salir? Necesitará iniciar sesión nuevamente." },
  "Sim, sair": { pt: "Sim, sair", en: "Yes, sign out", es: "Sí, salir" },
  "Matriz": { pt: "Matriz", en: "Headquarters", es: "Matriz" },
  "membros ativos": { pt: "membros ativos", en: "active members", es: "miembros activos" },
  "Receita do Mês": { pt: "Receita do Mês", en: "Monthly Revenue", es: "Ingresos del Mes" },
  "Despesas do Mês": { pt: "Despesas do Mês", en: "Monthly Expenses", es: "Gastos del Mes" },
  "Membros Ativos": { pt: "Membros Ativos", en: "Active Members", es: "Miembros Activos" },
  "Eventos no Mês": { pt: "Eventos no Mês", en: "Monthly Events", es: "Eventos del Mes" },
  "Próximos Eventos": { pt: "Próximos Eventos", en: "Upcoming Events", es: "Próximos Eventos" },
  "Ver todos": { pt: "Ver todos", en: "View all", es: "Ver todos" },
  "Nenhum evento próximo": { pt: "Nenhum evento próximo", en: "No upcoming events", es: "Sin eventos próximos" },
  "Avisos": { pt: "Avisos", en: "Notices", es: "Avisos" },
  "Acesso Rápido": { pt: "Acesso Rápido", en: "Quick Access", es: "Acceso Rápido" },
  "Novo Evento": { pt: "Novo Evento", en: "New Event", es: "Nuevo Evento" },
  "Marcar todos como lidos": { pt: "Marcar todos como lidos", en: "Mark all as read", es: "Marcar todos como leídos" },
  "Controle financeiro e relatórios": { pt: "Controle financeiro e relatórios", en: "Financial control and reports", es: "Control financiero e informes" },
  "Cadastro e gestão de membros": { pt: "Cadastro e gestão de membros", en: "Member registration and management", es: "Registro y gestión de miembros" },
  "Calendário e eventos da igreja": { pt: "Calendário e eventos da igreja", en: "Church calendar and events", es: "Calendario y eventos de la iglesia" },
  "Leitura e estudo bíblico": { pt: "Leitura e estudo bíblico", en: "Bible reading and study", es: "Lectura y estudio bíblico" },

  // Financeiro
  "Tesouraria e controle contábil": { pt: "Tesouraria e controle contábil", en: "Treasury and accounting", es: "Tesorería y contabilidad" },
  "Lançamento": { pt: "Lançamento", en: "New Entry", es: "Nuevo Registro" },
  "Novo Lançamento": { pt: "Novo Lançamento", en: "New Entry", es: "Nuevo Registro" },
  "Salvar Lançamento": { pt: "Salvar Lançamento", en: "Save Entry", es: "Guardar Registro" },
  "Movimentações Recentes": { pt: "Movimentações Recentes", en: "Recent Transactions", es: "Movimientos Recientes" },
  "Receita Total": { pt: "Receita Total", en: "Total Revenue", es: "Ingresos Totales" },
  "Despesas Totais": { pt: "Despesas Totais", en: "Total Expenses", es: "Gastos Totales" },
  "Saldo Atual": { pt: "Saldo Atual", en: "Current Balance", es: "Saldo Actual" },
  "Reserva": { pt: "Reserva", en: "Reserve", es: "Reserva" },
  "Chave PIX da Igreja": { pt: "Chave PIX da Igreja", en: "Church PIX Key", es: "Clave PIX de la Iglesia" },
  "Copiar Chave PIX": { pt: "Copiar Chave PIX", en: "Copy PIX Key", es: "Copiar Clave PIX" },
  "Chave copiada!": { pt: "Chave copiada!", en: "Key copied!", es: "¡Clave copiada!" },
  "Dizimar via PIX": { pt: "Dizimar via PIX", en: "Tithe via PIX", es: "Diezmo via PIX" },
  "Descrição": { pt: "Descrição", en: "Description", es: "Descripción" },
  "Valor (ex: 1500)": { pt: "Valor (ex: 1500)", en: "Amount (e.g. 1500)", es: "Monto (ej: 1500)" },
  "Categoria": { pt: "Categoria", en: "Category", es: "Categoría" },
  "Entrada": { pt: "Entrada", en: "Income", es: "Ingreso" },
  "Saída": { pt: "Saída", en: "Expense", es: "Gasto" },
  "Entradas": { pt: "Entradas", en: "Income", es: "Ingresos" },
  "Saídas": { pt: "Saídas", en: "Expenses", es: "Gastos" },
  "Data": { pt: "Data", en: "Date", es: "Fecha" },
  "Tipo": { pt: "Tipo", en: "Type", es: "Tipo" },
  "Valor": { pt: "Valor", en: "Amount", es: "Monto" },
  "Status": { pt: "Status", en: "Status", es: "Estado" },
  "Nenhuma movimentação encontrada.": { pt: "Nenhuma movimentação encontrada.", en: "No transactions found.", es: "No se encontraron movimientos." },
  "Lançamento salvo!": { pt: "Lançamento salvo!", en: "Entry saved!", es: "¡Registro guardado!" },

  // Membros
  "cadastrados": { pt: "cadastrados", en: "registered", es: "registrados" },
  "ativos": { pt: "ativos", en: "active", es: "activos" },
  "visitantes": { pt: "visitantes", en: "visitors", es: "visitantes" },
  "Novo Membro": { pt: "Novo Membro", en: "New Member", es: "Nuevo Miembro" },
  "Cadastrar Membro": { pt: "Cadastrar Membro", en: "Register Member", es: "Registrar Miembro" },
  "Nome completo": { pt: "Nome completo", en: "Full name", es: "Nombre completo" },
  "Função": { pt: "Função", en: "Role", es: "Función" },
  "Telefone": { pt: "Telefone", en: "Phone", es: "Teléfono" },
  "Contato": { pt: "Contato", en: "Contact", es: "Contacto" },
  "Desde": { pt: "Desde", en: "Since", es: "Desde" },
  "Ações": { pt: "Ações", en: "Actions", es: "Acciones" },
  "Salvar Membro": { pt: "Salvar Membro", en: "Save Member", es: "Guardar Miembro" },
  "Buscar por nome, função ou e-mail...": { pt: "Buscar por nome, função ou e-mail...", en: "Search by name, role or email...", es: "Buscar por nombre, función o email..." },
  "Nenhum membro encontrado.": { pt: "Nenhum membro encontrado.", en: "No members found.", es: "Ningún miembro encontrado." },
  "Membro cadastrado!": { pt: "Membro cadastrado!", en: "Member registered!", es: "¡Miembro registrado!" },
  "Membro removido": { pt: "Membro removido", en: "Member removed", es: "Miembro eliminado" },
  "Ativo": { pt: "Ativo", en: "Active", es: "Activo" },
  "Inativo": { pt: "Inativo", en: "Inactive", es: "Inactivo" },
  "Visitante": { pt: "Visitante", en: "Visitor", es: "Visitante" },
  "Nome": { pt: "Nome", en: "Name", es: "Nombre" },

  // Agenda
  "Lista": { pt: "Lista", en: "List", es: "Lista" },
  "Calendário": { pt: "Calendário", en: "Calendar", es: "Calendario" },
  "Evento": { pt: "Evento", en: "Event", es: "Evento" },
  "Título do evento": { pt: "Título do evento", en: "Event title", es: "Título del evento" },
  "Horário (ex: 09:00 - 11:00)": { pt: "Horário (ex: 09:00 - 11:00)", en: "Time (e.g. 09:00 - 11:00)", es: "Horario (ej: 09:00 - 11:00)" },
  "Local": { pt: "Local", en: "Location", es: "Lugar" },
  "Cor": { pt: "Cor", en: "Color", es: "Color" },
  "Dourado": { pt: "Dourado", en: "Gold", es: "Dorado" },
  "Azul": { pt: "Azul", en: "Blue", es: "Azul" },
  "Verde": { pt: "Verde", en: "Green", es: "Verde" },
  "Salvar Evento": { pt: "Salvar Evento", en: "Save Event", es: "Guardar Evento" },
  "Nenhum evento neste mês.": { pt: "Nenhum evento neste mês.", en: "No events this month.", es: "Sin eventos este mes." },
  "Nenhum evento neste dia.": { pt: "Nenhum evento neste dia.", en: "No events this day.", es: "Sin eventos este día." },
  "Evento salvo!": { pt: "Evento salvo!", en: "Event saved!", es: "¡Evento guardado!" },
  "Evento removido": { pt: "Evento removido", en: "Event removed", es: "Evento eliminado" },
  "Hoje": { pt: "Hoje", en: "Today", es: "Hoy" },
  "Passado": { pt: "Passado", en: "Past", es: "Pasado" },
  "Adicionar": { pt: "+ Adicionar", en: "+ Add", es: "+ Agregar" },
  "Eventos em": { pt: "Eventos em", en: "Events on", es: "Eventos en" },
  // Month names
  "Janeiro": { pt: "Janeiro", en: "January", es: "Enero" },
  "Fevereiro": { pt: "Fevereiro", en: "February", es: "Febrero" },
  "Março": { pt: "Março", en: "March", es: "Marzo" },
  "Abril": { pt: "Abril", en: "April", es: "Abril" },
  "Maio": { pt: "Maio", en: "May", es: "Mayo" },
  "Junho": { pt: "Junho", en: "June", es: "Junio" },
  "Julho": { pt: "Julho", en: "July", es: "Julio" },
  "Agosto": { pt: "Agosto", en: "August", es: "Agosto" },
  "Setembro": { pt: "Setembro", en: "September", es: "Septiembre" },
  "Outubro": { pt: "Outubro", en: "October", es: "Octubre" },
  "Novembro": { pt: "Novembro", en: "November", es: "Noviembre" },
  "Dezembro": { pt: "Dezembro", en: "December", es: "Diciembre" },
  // Day names
  "Dom": { pt: "Dom", en: "Sun", es: "Dom" },
  "Seg": { pt: "Seg", en: "Mon", es: "Lun" },
  "Ter": { pt: "Ter", en: "Tue", es: "Mar" },
  "Qua": { pt: "Qua", en: "Wed", es: "Mié" },
  "Qui": { pt: "Qui", en: "Thu", es: "Jue" },
  "Sex": { pt: "Sex", en: "Fri", es: "Vie" },
  "Sáb": { pt: "Sáb", en: "Sat", es: "Sáb" },

  // Bible
  "Leitura e meditação — Tradução Almeida": { pt: "Leitura e meditação — Tradução Almeida", en: "Reading & meditation — Almeida Translation", es: "Lectura y meditación — Traducción Almeida" },
  "Letras Gigantes": { pt: "Letras Gigantes", en: "Large Font", es: "Letra Grande" },
  "Assistente IA": { pt: "Assistente IA", en: "AI Assistant", es: "Asistente IA" },
  "Modo Zen": { pt: "Modo Zen", en: "Zen Mode", es: "Modo Zen" },
  "Selecionar Livro": { pt: "Selecionar Livro", en: "Select Book", es: "Seleccionar Libro" },
  "Buscar livro...": { pt: "Buscar livro...", en: "Search book...", es: "Buscar libro..." },
  "Antigo Testamento": { pt: "Antigo Testamento", en: "Old Testament", es: "Antiguo Testamento" },
  "Novo Testamento": { pt: "Novo Testamento", en: "New Testament", es: "Nuevo Testamento" },
  "capítulos": { pt: "capítulos", en: "chapters", es: "capítulos" },
  "Pergunte sobre a Bíblia...": { pt: "Pergunte sobre a Bíblia...", en: "Ask about the Bible...", es: "Pregunta sobre la Biblia..." },
  "Assistente Bíblico": { pt: "Assistente Bíblico", en: "Bible Assistant", es: "Asistente Bíblico" },
  "Assistente Bíblico com IA": { pt: "Assistente Bíblico com IA", en: "AI Bible Assistant", es: "Asistente Bíblico con IA" },
  "Faça perguntas, peça esboços e estudos profundos.": { pt: "Faça perguntas, peça esboços e estudos profundos.", en: "Ask questions, request outlines and deep studies.", es: "Haz preguntas, pide bosquejos y estudios profundos." },
  "Anterior": { pt: "Anterior", en: "Previous", es: "Anterior" },
  "Próximo": { pt: "Próximo", en: "Next", es: "Siguiente" },
  "Esboço de pregação": { pt: "Esboço de pregação", en: "Sermon outline", es: "Bosquejo de predicación" },
  "Estudo profundo": { pt: "Estudo profundo", en: "Deep study", es: "Estudio profundo" },
  "Contexto histórico": { pt: "Contexto histórico", en: "Historical context", es: "Contexto histórico" },
  "Aplicação prática": { pt: "Aplicação prática", en: "Practical application", es: "Aplicación práctica" },
  "Crie um esboço completo de pregação sobre": { pt: "Crie um esboço completo de pregação sobre", en: "Create a complete sermon outline about", es: "Crea un bosquejo completo de predicación sobre" },
  "Faça um estudo bíblico profundo sobre": { pt: "Faça um estudo bíblico profundo sobre", en: "Do a deep Bible study on", es: "Haz un estudio bíblico profundo sobre" },
  "Explique o contexto histórico de": { pt: "Explique o contexto histórico de", en: "Explain the historical context of", es: "Explica el contexto histórico de" },
  "Quais são as aplicações práticas de": { pt: "Quais são as aplicações práticas de", en: "What are the practical applications of", es: "Cuáles son las aplicaciones prácticas de" },

  // Oracoes
  "Compartilhe e interceda pelos pedidos da comunidade": { pt: "Compartilhe e interceda pelos pedidos da comunidade", en: "Share and pray for community requests", es: "Comparte e intercede por los pedidos de la comunidad" },
  "Novo Pedido": { pt: "Novo Pedido", en: "New Request", es: "Nuevo Pedido" },
  "Respondido": { pt: "Respondido", en: "Answered", es: "Respondido" },
  "Nenhum pedido de oração encontrado": { pt: "Nenhum pedido de oração encontrado", en: "No prayer requests found", es: "No se encontraron peticiones" },
  "Anônimo": { pt: "Anônimo", en: "Anonymous", es: "Anónimo" },
  "Membro": { pt: "Membro", en: "Member", es: "Miembro" },
  "orando": { pt: "orando", en: "praying", es: "orando" },
  "Estou orando": { pt: "🙏 Estou orando", en: "🙏 Praying", es: "🙏 Orando" },
  "AMÉM": { pt: "🙌 AMÉM", en: "🙌 AMEN", es: "🙌 AMÉN" },
  "Novo Pedido de Oração": { pt: "Novo Pedido de Oração", en: "New Prayer Request", es: "Nuevo Pedido de Oración" },
  "Título do pedido": { pt: "Título do pedido", en: "Request title", es: "Título del pedido" },
  "Descrição (opcional)": { pt: "Descrição (opcional)", en: "Description (optional)", es: "Descripción (opcional)" },
  "Enviar de forma anônima": { pt: "Enviar de forma anônima", en: "Send anonymously", es: "Enviar de forma anónima" },
  "Enviar Pedido": { pt: "Enviar Pedido", en: "Submit Request", es: "Enviar Pedido" },
  "Pedido registrado!": { pt: "Pedido registrado!", en: "Request submitted!", es: "¡Pedido registrado!" },

  // Comunicacao
  "Avisos e comunicados para a comunidade": { pt: "Avisos e comunicados para a comunidade", en: "Notices and announcements for the community", es: "Avisos y comunicados para la comunidad" },
  "Novo Comunicado": { pt: "Novo Comunicado", en: "New Announcement", es: "Nuevo Comunicado" },
  "Nenhum comunicado publicado": { pt: "Nenhum comunicado publicado", en: "No announcements published", es: "No hay comunicados publicados" },
  "Título": { pt: "Título", en: "Title", es: "Título" },
  "Conteúdo do comunicado": { pt: "Conteúdo do comunicado", en: "Announcement content", es: "Contenido del comunicado" },
  "Prioridade": { pt: "Prioridade", en: "Priority", es: "Prioridad" },
  "Normal": { pt: "Normal", en: "Normal", es: "Normal" },
  "Importante": { pt: "Importante", en: "Important", es: "Importante" },
  "Urgente": { pt: "Urgente", en: "Urgent", es: "Urgente" },
  "Comunicado publicado!": { pt: "Comunicado publicado!", en: "Announcement published!", es: "¡Comunicado publicado!" },

  // Grupos
  "Gerencie os grupos de comunhão e estudo": { pt: "Gerencie os grupos de comunhão e estudo", en: "Manage fellowship and study groups", es: "Gestione los grupos de comunión y estudio" },
  "Novo Grupo": { pt: "Novo Grupo", en: "New Group", es: "Nuevo Grupo" },
  "Nenhum grupo cadastrado": { pt: "Nenhum grupo cadastrado", en: "No groups registered", es: "Ningún grupo registrado" },
  "Nome do grupo": { pt: "Nome do grupo", en: "Group name", es: "Nombre del grupo" },
  "Nome do líder": { pt: "Nome do líder", en: "Leader name", es: "Nombre del líder" },
  "Dia (ex: Quarta)": { pt: "Dia (ex: Quarta)", en: "Day (e.g. Wednesday)", es: "Día (ej: Miércoles)" },
  "Horário": { pt: "Horário", en: "Time", es: "Horario" },
  "Descrição (opcional, grupos)": { pt: "Descrição (opcional)", en: "Description (optional)", es: "Descripción (opcional)" },
  "Máx. membros": { pt: "Máx. membros", en: "Max members", es: "Máx. miembros" },
  "Criar Grupo": { pt: "Criar Grupo", en: "Create Group", es: "Crear Grupo" },
  "Grupo criado!": { pt: "Grupo criado!", en: "Group created!", es: "¡Grupo creado!" },
  "Líder": { pt: "Líder", en: "Leader", es: "Líder" },
  "membros": { pt: "membros", en: "members", es: "miembros" },

  // Documentos
  "Biblioteca de documentos da igreja": { pt: "Biblioteca de documentos da igreja", en: "Church documents library", es: "Biblioteca de documentos de la iglesia" },
  "Novo Documento": { pt: "Novo Documento", en: "New Document", es: "Nuevo Documento" },
  "Nenhum documento encontrado": { pt: "Nenhum documento encontrado", en: "No documents found", es: "No se encontraron documentos" },
  "Título do documento": { pt: "Título do documento", en: "Document title", es: "Título del documento" },
  "Documento registrado!": { pt: "Documento registrado!", en: "Document registered!", es: "¡Documento registrado!" },
  "Geral": { pt: "Geral", en: "General", es: "General" },
  "Atas": { pt: "Atas", en: "Minutes", es: "Actas" },
  "Estatuto": { pt: "Estatuto", en: "Statute", es: "Estatuto" },
  "Ministerial": { pt: "Ministerial", en: "Ministerial", es: "Ministerial" },

  // Relatorios
  "Total de Membros": { pt: "Total de Membros", en: "Total Members", es: "Total de Miembros" },
  "Receita do Mês (relatório)": { pt: "Receita do Mês", en: "Monthly Revenue", es: "Ingresos del Mes" },
  "Despesa do Mês": { pt: "Despesa do Mês", en: "Monthly Expense", es: "Gasto del Mes" },
  "Carregando relatórios...": { pt: "Carregando relatórios...", en: "Loading reports...", es: "Cargando informes..." },
  "respondidos": { pt: "respondidos", en: "answered", es: "respondidos" },
  "Visão geral de": { pt: "Visão geral de", en: "Overview of", es: "Visión general de" },

  // Escalas
  "Escalas de Serviço": { pt: "Escalas de Serviço", en: "Service Schedules", es: "Escalas de Servicio" },
  "Organize as escalas por ministério": { pt: "Organize as escalas por ministério", en: "Organize schedules by ministry", es: "Organice las escalas por ministerio" },
  "Nova Escala": { pt: "Nova Escala", en: "New Schedule", es: "Nueva Escala" },
  "Nenhuma escala encontrada": { pt: "Nenhuma escala encontrada", en: "No schedules found", es: "No se encontraron escalas" },
  "Título (ex: Culto Domingo)": { pt: "Título (ex: Culto Domingo)", en: "Title (e.g. Sunday Service)", es: "Título (ej: Culto Domingo)" },
  "Ministério": { pt: "Ministério", en: "Ministry", es: "Ministerio" },
  "Responsável(is)": { pt: "Responsável(is)", en: "Assigned to", es: "Responsable(s)" },
  "Observações (opcional)": { pt: "Observações (opcional)", en: "Notes (optional)", es: "Observaciones (opcional)" },
  "Criar Escala": { pt: "Criar Escala", en: "Create Schedule", es: "Crear Escala" },
  "Escala criada!": { pt: "Escala criada!", en: "Schedule created!", es: "¡Escala creada!" },
  "Louvor": { pt: "Louvor", en: "Worship", es: "Alabanza" },
  "Infantil": { pt: "Infantil", en: "Children", es: "Infantil" },
  "Mídia": { pt: "Mídia", en: "Media", es: "Medios" },
  "Recepção": { pt: "Recepção", en: "Reception", es: "Recepción" },
  "Intercessão": { pt: "Intercessão", en: "Intercession", es: "Intercesión" },
  "Pregação": { pt: "Pregação", en: "Preaching", es: "Predicación" },
  "Confirmado": { pt: "Confirmado", en: "Confirmed", es: "Confirmado" },
  "Pendente": { pt: "Pendente", en: "Pending", es: "Pendiente" },

  // Profile
  "Meu Perfil": { pt: "Meu Perfil", en: "My Profile", es: "Mi Perfil" },
  "Gerencie suas informações pessoais": { pt: "Gerencie suas informações pessoais", en: "Manage your personal information", es: "Gestione su información personal" },
  "Nome Completo": { pt: "Nome Completo", en: "Full Name", es: "Nombre Completo" },
  "Função na Igreja": { pt: "Função na Igreja", en: "Church Role", es: "Función en la Iglesia" },
  "Clique no ícone para alterar a foto": { pt: "Clique no ícone para alterar a foto", en: "Click the icon to change the photo", es: "Haga clic en el icono para cambiar la foto" },
  "Salvar Alterações": { pt: "Salvar Alterações", en: "Save Changes", es: "Guardar Cambios" },
  "Perfil atualizado com sucesso!": { pt: "Perfil atualizado com sucesso!", en: "Profile updated successfully!", es: "¡Perfil actualizado con éxito!" },
  "Foto atualizada!": { pt: "Foto atualizada!", en: "Photo updated!", es: "¡Foto actualizada!" },

  // Access management
  "Defina quem pode acessar cada módulo do sistema": { pt: "Defina quem pode acessar cada módulo do sistema", en: "Define who can access each system module", es: "Defina quién puede acceder a cada módulo del sistema" },
  "Funções disponíveis": { pt: "Funções disponíveis", en: "Available roles", es: "Funciones disponibles" },
  "Sem nome": { pt: "Sem nome", en: "No name", es: "Sin nombre" },
  "(você)": { pt: "(você)", en: "(you)", es: "(tú)" },
  "Função atualizada para": { pt: "Função atualizada para", en: "Role updated to", es: "Función actualizada a" },

  // Landing
  "Entrar": { pt: "Entrar", en: "Sign in", es: "Entrar" },
  "Gestão eclesiástica de excelência": { pt: "Gestão eclesiástica de excelência", en: "Excellence in church management", es: "Gestión eclesiástica de excelencia" },
  "A excelência na gestão": { pt: "A excelência na gestão", en: "Excellence in management", es: "La excelencia en la gestión" },
  "a serviço do Reino.": { pt: "a serviço do Reino.", en: "at the service of the Kingdom.", es: "al servicio del Reino." },
  "Um sistema completo, sofisticado e confiável para administrar sua igreja com a seriedade que ela merece.": { pt: "Um sistema completo, sofisticado e confiável para administrar sua igreja com a seriedade que ela merece.", en: "A complete, sophisticated and reliable system to manage your church with the seriousness it deserves.", es: "Un sistema completo, sofisticado y confiable para administrar su iglesia con la seriedad que merece." },
  "Acessar o Sistema": { pt: "Acessar o Sistema", en: "Access System", es: "Acceder al Sistema" },
  "Conhecer Módulos": { pt: "Conhecer Módulos", en: "Explore Modules", es: "Conocer Módulos" },
  "Módulos do Sistema": { pt: "Módulos do Sistema", en: "System Modules", es: "Módulos del Sistema" },
  "Cada módulo foi projetado com precisão para atender às necessidades reais da sua igreja.": { pt: "Cada módulo foi projetado com precisão para atender às necessidades reais da sua igreja.", en: "Each module is precisely designed to meet the real needs of your church.", es: "Cada módulo fue diseñado con precisión para atender las necesidades reales de su iglesia." },
  "Pronto para transformar a gestão da sua igreja?": { pt: "Pronto para transformar a gestão da sua igreja?", en: "Ready to transform your church management?", es: "¿Listo para transformar la gestión de su iglesia?" },
  "Comece agora e eleve o nível de organização da sua comunidade.": { pt: "Comece agora e eleve o nível de organização da sua comunidade.", en: "Start now and elevate your community's organization.", es: "Comience ahora y eleve el nivel de organización de su comunidad." },
  "Começar Agora": { pt: "Começar Agora", en: "Start Now", es: "Comenzar Ahora" },
  "Dashboard Executivo": { pt: "Dashboard Executivo", en: "Executive Dashboard", es: "Panel Ejecutivo" },
  "Visão gerencial completa com métricas em tempo real.": { pt: "Visão gerencial completa com métricas em tempo real.", en: "Complete management view with real-time metrics.", es: "Visión gerencial completa con métricas en tiempo real." },
  "Tesouraria": { pt: "Tesouraria", en: "Treasury", es: "Tesorería" },
  "Controle financeiro robusto com relatórios detalhados.": { pt: "Controle financeiro robusto com relatórios detalhados.", en: "Robust financial control with detailed reports.", es: "Control financiero robusto con informes detallados." },
  "Gestão de Membros": { pt: "Gestão de Membros", en: "Member Management", es: "Gestión de Miembros" },
  "Cadastro completo de membros e visitantes.": { pt: "Cadastro completo de membros e visitantes.", en: "Complete registration of members and visitors.", es: "Registro completo de miembros y visitantes." },
  "Agenda Integrada": { pt: "Agenda Integrada", en: "Integrated Calendar", es: "Agenda Integrada" },
  "Calendário institucional para toda a comunidade.": { pt: "Calendário institucional para toda a comunidade.", en: "Institutional calendar for the whole community.", es: "Calendario institucional para toda la comunidad." },
  "Leitura confortável com modo noturno integrado.": { pt: "Leitura confortável com modo noturno integrado.", en: "Comfortable reading with integrated dark mode.", es: "Lectura cómoda con modo nocturno integrado." },
  "Acompanhamento pastoral e intercessão comunitária.": { pt: "Acompanhamento pastoral e intercessão comunitária.", en: "Pastoral care and community intercession.", es: "Acompañamiento pastoral e intercesión comunitaria." },
  "Avisos, mensagens e comunicados centralizados.": { pt: "Avisos, mensagens e comunicados centralizados.", en: "Centralized notices, messages and announcements.", es: "Avisos, mensajes y comunicados centralizados." },
  "Dados estratégicos para tomada de decisão.": { pt: "Dados estratégicos para tomada de decisão.", en: "Strategic data for decision making.", es: "Datos estratégicos para toma de decisiones." },

  // Login / Signup
  "Bem-vindo de volta (login)": { pt: "Bem-vindo de volta", en: "Welcome back", es: "Bienvenido de vuelta" },
  "Entre com suas credenciais": { pt: "Entre com suas credenciais", en: "Sign in with your credentials", es: "Ingrese con sus credenciales" },
  "E-mail": { pt: "E-mail", en: "Email", es: "Correo electrónico" },
  "Senha": { pt: "Senha", en: "Password", es: "Contraseña" },
  "Esqueci a senha": { pt: "Esqueci a senha", en: "Forgot password", es: "Olvidé la contraseña" },
  "Entrar com Google": { pt: "Entrar com Google", en: "Sign in with Google", es: "Entrar con Google" },
  "Não tem conta?": { pt: "Não tem conta?", en: "Don't have an account?", es: "¿No tienes cuenta?" },
  "Criar conta": { pt: "Criar conta", en: "Create account", es: "Crear cuenta" },
  "Preencha os dados para começar": { pt: "Preencha os dados para começar", en: "Fill in the details to get started", es: "Complete los datos para comenzar" },
  "Cadastrar com Google": { pt: "Cadastrar com Google", en: "Sign up with Google", es: "Registrarse con Google" },
  "Já tem conta?": { pt: "Já tem conta?", en: "Already have an account?", es: "¿Ya tienes cuenta?" },
  "Conta criada!": { pt: "Conta criada!", en: "Account created!", es: "¡Cuenta creada!" },
  "Verifique seu e-mail para confirmar o cadastro.": { pt: "Verifique seu e-mail para confirmar o cadastro.", en: "Check your email to confirm your registration.", es: "Verifique su correo electrónico para confirmar el registro." },
  "Mínimo 6 caracteres": { pt: "Mínimo 6 caracteres", en: "Minimum 6 characters", es: "Mínimo 6 caracteres" },

  // Invite system
  "Convidar pessoa": { pt: "Convidar pessoa", en: "Invite person", es: "Invitar persona" },
  "Compartilhar via WhatsApp": { pt: "Compartilhar via WhatsApp", en: "Share via WhatsApp", es: "Compartir vía WhatsApp" },
  "Compartilhar via E-mail": { pt: "Compartilhar via E-mail", en: "Share via Email", es: "Compartir vía E-mail" },
  "Copiar link de convite": { pt: "Copiar link de convite", en: "Copy invite link", es: "Copiar link de invitación" },
  "Link copiado!": { pt: "Link copiado!", en: "Link copied!", es: "¡Link copiado!" },
  "Selecione a função para o convidado": { pt: "Selecione a função para o convidado", en: "Select the role for the guest", es: "Seleccione la función para el invitado" },

  // Footer
  "Todos os direitos reservados.": { pt: "Todos os direitos reservados.", en: "All rights reserved.", es: "Todos los derechos reservados." },

  // Fullscreen
  "Tela cheia": { pt: "Tela cheia", en: "Fullscreen", es: "Pantalla completa" },
  "Sair da tela cheia": { pt: "Sair da tela cheia", en: "Exit fullscreen", es: "Salir de pantalla completa" },

  // Bible extra
  "Selecione um capítulo acima para começar a leitura": { pt: "Selecione um capítulo acima para começar a leitura", en: "Select a chapter above to start reading", es: "Seleccione un capítulo arriba para comenzar la lectura" },
  "Toque para perguntar, pedir esboços e estudos": { pt: "Toque para perguntar, pedir esboços e estudos", en: "Tap to ask questions, request outlines and studies", es: "Toque para preguntar, pedir bosquejos y estudios" },
  "Capítulo": { pt: "Capítulo", en: "Chapter", es: "Capítulo" },
  "Não foi possível carregar este capítulo.": { pt: "Não foi possível carregar este capítulo.", en: "Could not load this chapter.", es: "No fue posible cargar este capítulo." },
  "Tentar novamente": { pt: "Tentar novamente", en: "Try again", es: "Intentar de nuevo" },
  "Limpar conversa": { pt: "Limpar conversa", en: "Clear conversation", es: "Limpiar conversación" },
  "Falar com microfone": { pt: "Falar com microfone", en: "Speak with microphone", es: "Hablar con micrófono" },
  "Baixar": { pt: "Baixar", en: "Download", es: "Descargar" },
  "Compartilhar": { pt: "Compartilhar", en: "Share", es: "Compartir" },
  "Pesquisa por voz": { pt: "Pesquisa por voz", en: "Voice search", es: "Búsqueda por voz" },

  // Forgot / Reset password
  "Recuperar senha": { pt: "Recuperar senha", en: "Recover password", es: "Recuperar contraseña" },
  "Enviaremos um link para redefinir sua senha": { pt: "Enviaremos um link para redefinir sua senha", en: "We'll send a link to reset your password", es: "Le enviaremos un enlace para restablecer su contraseña" },
  "Enviar link": { pt: "Enviar link", en: "Send link", es: "Enviar enlace" },
  "Voltar ao login": { pt: "Voltar ao login", en: "Back to login", es: "Volver al inicio de sesión" },
  "E-mail enviado para": { pt: "E-mail enviado para", en: "Email sent to", es: "Correo enviado a" },
  "Verifique sua caixa de entrada e siga as instruções.": { pt: "Verifique sua caixa de entrada e siga as instruções.", en: "Check your inbox and follow the instructions.", es: "Revise su bandeja de entrada y siga las instrucciones." },
  "Erro ao entrar": { pt: "Erro ao entrar", en: "Login error", es: "Error al iniciar sesión" },
  "Erro ao criar conta": { pt: "Erro ao criar conta", en: "Error creating account", es: "Error al crear cuenta" },

  // Agenda extra
  "evento": { pt: "evento", en: "event", es: "evento" },
  "eventos": { pt: "eventos", en: "events", es: "eventos" },
  "Novo Evento —": { pt: "Novo Evento —", en: "New Event —", es: "Nuevo Evento —" },
  "de": { pt: "de", en: "of", es: "de" },

  // GerenciarAcessos extra
  "Administrador": { pt: "Administrador", en: "Administrator", es: "Administrador" },
  "Tesoureiro": { pt: "Tesoureiro", en: "Treasurer", es: "Tesorero" },
  "Obreiro": { pt: "Obreiro", en: "Worker", es: "Obrero" },
  "Líder de Grupo": { pt: "Líder de Grupo", en: "Group Leader", es: "Líder de Grupo" },
  "Acesso total ao sistema. Pode gerenciar outros usuários.": { pt: "Acesso total ao sistema. Pode gerenciar outros usuários.", en: "Full system access. Can manage other users.", es: "Acceso total al sistema. Puede gestionar otros usuarios." },
  "Acesso a Financeiro e Relatórios.": { pt: "Acesso a Financeiro e Relatórios.", en: "Access to Finances and Reports.", es: "Acceso a Finanzas e Informes." },
  "Acesso a Agenda, Comunicação, Documentos e Escalas.": { pt: "Acesso a Agenda, Comunicação, Documentos e Escalas.", en: "Access to Calendar, Communication, Documents and Schedules.", es: "Acceso a Agenda, Comunicación, Documentos y Escalas." },
  "Acesso a Agenda e Pequenos Grupos.": { pt: "Acesso a Agenda e Pequenos Grupos.", en: "Access to Calendar and Small Groups.", es: "Acceso a Agenda y Grupos Pequeños." },
  "Acesso apenas à Bíblia e Pedidos de Oração.": { pt: "Acesso apenas à Bíblia e Pedidos de Oração.", en: "Access only to Bible and Prayer Requests.", es: "Acceso solo a Biblia y Peticiones de Oración." },

  // Dashboard cards
  "Bem-vindo ao sistema de gestão da igreja!": { pt: "Bem-vindo ao sistema de gestão da igreja!", en: "Welcome to the church management system!", es: "¡Bienvenido al sistema de gestión de la iglesia!" },
  "Agora": { pt: "Agora", en: "Now", es: "Ahora" },

  // Misc
  "Pago": { pt: "Pago", en: "Paid", es: "Pagado" },
  "Erro ao salvar": { pt: "Erro ao salvar", en: "Error saving", es: "Error al guardar" },
  "Erro ao carregar eventos": { pt: "Erro ao carregar eventos", en: "Error loading events", es: "Error al cargar eventos" },
  "Erro ao remover evento": { pt: "Erro ao remover evento", en: "Error removing event", es: "Error al eliminar evento" },
  "Erro ao carregar transações": { pt: "Erro ao carregar transações", en: "Error loading transactions", es: "Error al cargar transacciones" },
  "Erro ao enviar foto": { pt: "Erro ao enviar foto", en: "Error uploading photo", es: "Error al subir foto" },
  "Erro ao atualizar": { pt: "Erro ao atualizar", en: "Error updating", es: "Error al actualizar" },
  "Erro ao carregar membros": { pt: "Erro ao carregar membros", en: "Error loading members", es: "Error al cargar miembros" },
  "Erro ao remover": { pt: "Erro ao remover", en: "Error removing", es: "Error al eliminar" },
  "Erro ao buscar versículos": { pt: "Erro ao buscar versículos", en: "Error fetching verses", es: "Error al buscar versículos" },
  "A definir": { pt: "A definir", en: "TBD", es: "Por definir" },
  "Texto copiado!": { pt: "Texto copiado!", en: "Text copied!", es: "¡Texto copiado!" },
  "Seu navegador não suporta reconhecimento de voz. Tente usar o Google Chrome.": { pt: "Seu navegador não suporta reconhecimento de voz. Tente usar o Google Chrome.", en: "Your browser does not support voice recognition. Try using Google Chrome.", es: "Su navegador no soporta reconocimiento de voz. Intente usar Google Chrome." },
  "Permissão de microfone negada. Verifique as configurações do seu navegador.": { pt: "Permissão de microfone negada. Verifique as configurações do seu navegador.", en: "Microphone permission denied. Check your browser settings.", es: "Permiso de micrófono denegado. Verifique la configuración de su navegador." },
  "Nenhuma fala detectada. Tente novamente.": { pt: "Nenhuma fala detectada. Tente novamente.", en: "No speech detected. Try again.", es: "No se detectó voz. Inténtelo de nuevo." },
  "Erro ao iniciar o microfone. Tente usar o Google Chrome.": { pt: "Erro ao iniciar o microfone. Tente usar o Google Chrome.", en: "Error starting microphone. Try using Google Chrome.", es: "Error al iniciar el micrófono. Intente usar Google Chrome." },
  "Ouvindo...": { pt: "Ouvindo...", en: "Listening...", es: "Escuchando..." },
  "Confirmar": { pt: "Confirmar", en: "Confirm", es: "Confirmar" },
  "redução": { pt: "redução", en: "reduction", es: "reducción" },

  // Congregações
  "Congregações": { pt: "Congregações", en: "Congregations", es: "Congregaciones" },
  "Gerencie as congregações vinculadas à matriz": { pt: "Gerencie as congregações vinculadas à matriz", en: "Manage congregations linked to headquarters", es: "Gestione las congregaciones vinculadas a la matriz" },
  "Visualize informações da sua congregação": { pt: "Visualize informações da sua congregação", en: "View your congregation information", es: "Visualice información de su congregación" },
  "Nova Congregação": { pt: "Nova Congregação", en: "New Congregation", es: "Nueva Congregación" },
  "Editar Congregação": { pt: "Editar Congregação", en: "Edit Congregation", es: "Editar Congregación" },
  "Nome da congregação *": { pt: "Nome da congregação *", en: "Congregation name *", es: "Nombre de la congregación *" },
  "Nome do pastor/líder": { pt: "Nome do pastor/líder", en: "Pastor/leader name", es: "Nombre del pastor/líder" },
  "Endereço": { pt: "Endereço", en: "Address", es: "Dirección" },
  "Cidade": { pt: "Cidade", en: "City", es: "Ciudad" },
  "Estado": { pt: "Estado", en: "State", es: "Estado" },
  "Criar Congregação": { pt: "Criar Congregação", en: "Create Congregation", es: "Crear Congregación" },
  "Congregação atualizada com sucesso!": { pt: "Congregação atualizada com sucesso!", en: "Congregation updated successfully!", es: "¡Congregación actualizada con éxito!" },
  "Congregação criada com sucesso!": { pt: "Congregação criada com sucesso!", en: "Congregation created successfully!", es: "¡Congregación creada con éxito!" },
  "Congregação excluída": { pt: "Congregação excluída", en: "Congregation deleted", es: "Congregación eliminada" },
  "Nome é obrigatório": { pt: "Nome é obrigatório", en: "Name is required", es: "El nombre es obligatorio" },
  "Erro ao criar congregação": { pt: "Erro ao criar congregação", en: "Error creating congregation", es: "Error al crear congregación" },
  "Erro ao excluir": { pt: "Erro ao excluir", en: "Error deleting", es: "Error al eliminar" },
  "Nenhuma congregação cadastrada": { pt: "Nenhuma congregação cadastrada", en: "No congregations registered", es: "Ninguna congregación registrada" },
  "Compartilhe este link para convidar membros para esta congregação.": { pt: "Compartilhe este link para convidar membros para esta congregação.", en: "Share this link to invite members to this congregation.", es: "Comparta este enlace para invitar miembros a esta congregación." },
  "Informações da Matriz": { pt: "Informações da Matriz", en: "Headquarters Information", es: "Información de la Matriz" },
  "Pastor": { pt: "Pastor", en: "Pastor", es: "Pastor" },
  "Total de Congregações": { pt: "Total de Congregações", en: "Total Congregations", es: "Total de Congregaciones" },
  "Editar": { pt: "Editar", en: "Edit", es: "Editar" },
  "Excluir": { pt: "Excluir", en: "Delete", es: "Eliminar" },

  // Biblia extras
  "Imagem": { pt: "Imagem", en: "Image", es: "Imagen" },
  "Documento": { pt: "Documento", en: "Document", es: "Documento" },
  "Anexar arquivo": { pt: "Anexar arquivo", en: "Attach file", es: "Adjuntar archivo" },
  "Estudo Bíblico": { pt: "Estudo Bíblico", en: "Bible Study", es: "Estudio Bíblico" },
  "Ex: Pastor, Diácono, Membro...": { pt: "Ex: Pastor, Diácono, Membro...", en: "E.g.: Pastor, Deacon, Member...", es: "Ej: Pastor, Diácono, Miembro..." },

  // Bulk Import Modal
  "Importar Dados": { pt: "Importar Dados", en: "Import Data", es: "Importar Datos" },
  "Arraste um arquivo CSV aqui": { pt: "Arraste um arquivo CSV aqui", en: "Drag a CSV file here", es: "Arrastre un archivo CSV aquí" },
  "ou clique para selecionar": { pt: "ou clique para selecionar", en: "or click to select", es: "o haga clic para seleccionar" },
  "Baixar modelo CSV": { pt: "Baixar modelo CSV", en: "Download CSV template", es: "Descargar modelo CSV" },
  "Dica: Exporte sua planilha do Excel como CSV (separado por vírgulas). A primeira linha deve conter os nomes das colunas.": { pt: "Dica: Exporte sua planilha do Excel como CSV (separado por vírgulas). A primeira linha deve conter os nomes das colunas.", en: "Tip: Export your Excel spreadsheet as CSV (comma-separated). The first row should contain column names.", es: "Consejo: Exporte su hoja de cálculo de Excel como CSV (separado por comas). La primera fila debe contener los nombres de las columnas." },
  "linhas": { pt: "linhas", en: "rows", es: "filas" },
  "Associe as colunas do CSV aos campos do sistema:": { pt: "Associe as colunas do CSV aos campos do sistema:", en: "Map CSV columns to system fields:", es: "Asocie las columnas del CSV a los campos del sistema:" },
  "— Não importar —": { pt: "— Não importar —", en: "— Don't import —", es: "— No importar —" },
  "Campos obrigatórios não mapeados:": { pt: "Campos obrigatórios não mapeados:", en: "Required fields not mapped:", es: "Campos obligatorios no mapeados:" },
  "Voltar": { pt: "Voltar", en: "Back", es: "Volver" },
  "Pré-visualizar": { pt: "Pré-visualizar", en: "Preview", es: "Previsualizar" },
  "Pré-visualização": { pt: "Pré-visualização", en: "Preview", es: "Previsualización" },
  "registros": { pt: "registros", en: "records", es: "registros" },
  "e mais": { pt: "e mais", en: "and more", es: "y más" },
  "Importando...": { pt: "Importando...", en: "Importing...", es: "Importando..." },
  "Importar": { pt: "Importar", en: "Import", es: "Importar" },
  "Importação concluída!": { pt: "Importação concluída!", en: "Import completed!", es: "¡Importación completada!" },
  "importados com sucesso": { pt: "importados com sucesso", en: "imported successfully", es: "importados con éxito" },
  "com erro": { pt: "com erro", en: "with errors", es: "con errores" },
  "Fechar": { pt: "Fechar", en: "Close", es: "Cerrar" },
  "Importar Membros": { pt: "Importar Membros", en: "Import Members", es: "Importar Miembros" },
  "Importar Lançamentos": { pt: "Importar Lançamentos", en: "Import Entries", es: "Importar Registros" },
  "Importar Documentos": { pt: "Importar Documentos", en: "Import Documents", es: "Importar Documentos" },
  "Importar CSV": { pt: "Importar CSV", en: "Import CSV", es: "Importar CSV" },

  // AI Import Modal
  "Importar com IA": { pt: "Importar com IA", en: "Import with AI", es: "Importar con IA" },
  "Importar Membros com IA": { pt: "Importar Membros com IA", en: "Import Members with AI", es: "Importar Miembros con IA" },
  "Importar Lançamentos com IA": { pt: "Importar Lançamentos com IA", en: "Import Entries with AI", es: "Importar Registros con IA" },
  "Importar Documentos com IA": { pt: "Importar Documentos com IA", en: "Import Documents with AI", es: "Importar Documentos con IA" },
  "Arraste um arquivo aqui": { pt: "Arraste um arquivo aqui", en: "Drag a file here", es: "Arrastre un archivo aquí" },
  "PDF, imagem, CSV ou texto": { pt: "PDF, imagem, CSV ou texto", en: "PDF, image, CSV or text", es: "PDF, imagen, CSV o texto" },
  "Fotos": { pt: "Fotos", en: "Photos", es: "Fotos" },
  "A IA não conseguiu extrair dados deste arquivo. Tente outro formato.": { pt: "A IA não conseguiu extrair dados deste arquivo. Tente outro formato.", en: "AI couldn't extract data from this file. Try another format.", es: "La IA no pudo extraer datos de este archivo. Intente otro formato." },
  "A IA vai analisar o arquivo e extrair os dados automaticamente. Você poderá revisar antes de importar.": { pt: "A IA vai analisar o arquivo e extrair os dados automaticamente. Você poderá revisar antes de importar.", en: "AI will analyze the file and extract data automatically. You can review before importing.", es: "La IA analizará el archivo y extraerá los datos automáticamente. Podrá revisar antes de importar." },
  "Analisando arquivo...": { pt: "Analisando arquivo...", en: "Analyzing file...", es: "Analizando archivo..." },
  "A IA está extraindo os dados do documento": { pt: "A IA está extraindo os dados do documento", en: "AI is extracting data from the document", es: "La IA está extrayendo los datos del documento" },
  "IA extraiu": { pt: "IA extraiu", en: "AI extracted", es: "La IA extrajo" },
  "Erro ao processar": { pt: "Erro ao processar", en: "Error processing", es: "Error al procesar" },

  // Assembleia Geral
  "Assembleia Geral": { pt: "Assembleia Geral", en: "General Assembly", es: "Asamblea General" },
  "Atas, relatórios e registros das assembleias da igreja": { pt: "Atas, relatórios e registros das assembleias da igreja", en: "Minutes, reports and records of church assemblies", es: "Actas, informes y registros de las asambleas de la iglesia" },
  "Nova Assembleia": { pt: "Nova Assembleia", en: "New Assembly", es: "Nueva Asamblea" },
  "Nenhuma assembleia registrada": { pt: "Nenhuma assembleia registrada", en: "No assemblies registered", es: "Ninguna asamblea registrada" },
  "Clique em 'Nova Assembleia' para começar": { pt: "Clique em 'Nova Assembleia' para começar", en: "Click 'New Assembly' to get started", es: "Haga clic en 'Nueva Asamblea' para comenzar" },
  "Visível": { pt: "Visível", en: "Visible", es: "Visible" },
  "Oculta": { pt: "Oculta", en: "Hidden", es: "Oculta" },
  "Ocultar": { pt: "Ocultar", en: "Hide", es: "Ocultar" },
  "Tornar visível": { pt: "Tornar visível", en: "Make visible", es: "Hacer visible" },
  "Anexos e Documentos": { pt: "Anexos e Documentos", en: "Attachments & Documents", es: "Anexos y Documentos" },
  "Título do anexo": { pt: "Título do anexo", en: "Attachment title", es: "Título del anexo" },
  "Selecionar arquivo": { pt: "Selecionar arquivo", en: "Select file", es: "Seleccionar archivo" },
  "Salvar Anexo": { pt: "Salvar Anexo", en: "Save Attachment", es: "Guardar Anexo" },
  "Assembleia criada!": { pt: "Assembleia criada!", en: "Assembly created!", es: "¡Asamblea creada!" },
  "Assembleia removida": { pt: "Assembleia removida", en: "Assembly removed", es: "Asamblea eliminada" },
  "Erro no upload": { pt: "Erro no upload", en: "Upload error", es: "Error en la subida" },
  "Anexo adicionado!": { pt: "Anexo adicionado!", en: "Attachment added!", es: "¡Anexo agregado!" },
  "Nenhum anexo ainda": { pt: "Nenhum anexo ainda", en: "No attachments yet", es: "Sin anexos aún" },
  "Ata": { pt: "Ata", en: "Minutes", es: "Acta" },
  "Relatório": { pt: "Relatório", en: "Report", es: "Informe" },
  "Vídeo (YouTube)": { pt: "Vídeo (YouTube)", en: "Video (YouTube)", es: "Video (YouTube)" },
  "Título da assembleia": { pt: "Título da assembleia", en: "Assembly title", es: "Título de la asamblea" },
  "Período (ex: 1º Trimestre 2026)": { pt: "Período (ex: 1º Trimestre 2026)", en: "Period (e.g. Q1 2026)", es: "Período (ej: 1er Trimestre 2026)" },
  "Link do YouTube (opcional)": { pt: "Link do YouTube (opcional)", en: "YouTube link (optional)", es: "Enlace de YouTube (opcional)" },
  "Criar Assembleia": { pt: "Criar Assembleia", en: "Create Assembly", es: "Crear Asamblea" },

  // Harpa / Hinário
  "Harpa - Hinário Digital": { pt: "Harpa - Hinário Digital", en: "Harpa - Digital Hymnal", es: "Harpa - Himnario Digital" },
  "Hinos clássicos da fé cristã com letra e áudio": { pt: "Hinos clássicos da fé cristã com letra e áudio", en: "Classic Christian hymns with lyrics and audio", es: "Himnos clásicos de la fe cristiana con letra y audio" },
  "Enviar Hino": { pt: "Enviar Hino", en: "Upload Hymn", es: "Subir Himno" },
  "Assistente de Hinos": { pt: "Assistente de Hinos", en: "Hymn Assistant", es: "Asistente de Himnos" },
  "Hinos Disponíveis": { pt: "Hinos Disponíveis", en: "Available Hymns", es: "Himnos Disponibles" },
  "Categorias": { pt: "Categorias", en: "Categories", es: "Categorías" },
  "Com Letra": { pt: "Com Letra", en: "With Lyrics", es: "Con Letra" },
  "Pergunte sobre hinos, peça sugestões...": { pt: "Pergunte sobre hinos, peça sugestões...", en: "Ask about hymns, request suggestions...", es: "Pregunte sobre himnos, pida sugerencias..." },
  "Escala de culto": { pt: "Escala de culto", en: "Service schedule", es: "Escala de culto" },
  "Hinos de adoração": { pt: "Hinos de adoração", en: "Worship hymns", es: "Himnos de adoración" },
  "Culto temático": { pt: "Culto temático", en: "Themed service", es: "Culto temático" },
  "Conexão bíblica": { pt: "Conexão bíblica", en: "Biblical connection", es: "Conexión bíblica" },
  "Harpa": { pt: "Harpa", en: "Harpa", es: "Harpa" },
  "Hinário digital com áudio": { pt: "Hinário digital com áudio", en: "Digital hymnal with audio", es: "Himnario digital con audio" },
  "Leia e medite na Palavra": { pt: "Leia e medite na Palavra", en: "Read and meditate on the Word", es: "Lea y medite en la Palabra" },
  "Ore pela igreja": { pt: "Ore pela igreja", en: "Pray for the church", es: "Ore por la iglesia" },
  "Comunicados da igreja": { pt: "Comunicados da igreja", en: "Church announcements", es: "Comunicados de la iglesia" },
  "Escalas de serviço": { pt: "Escalas de serviço", en: "Service schedules", es: "Escalas de servicio" },

  // Dashboard extras
  "Visão global da plataforma": { pt: "Visão global da plataforma", en: "Platform overview", es: "Visión global de la plataforma" },
  "Bem-vindo à sua igreja": { pt: "Bem-vindo à sua igreja", en: "Welcome to your church", es: "Bienvenido a su iglesia" },
  "Total de Usuários": { pt: "Total de Usuários", en: "Total Users", es: "Total de Usuarios" },
  "Gerenciar congregações": { pt: "Gerenciar congregações", en: "Manage congregations", es: "Gestionar congregaciones" },
  "Gestão global da plataforma": { pt: "Gestão global da plataforma", en: "Global platform management", es: "Gestión global de la plataforma" },
  "Nenhum aviso": { pt: "Nenhum aviso", en: "No notices", es: "Sin avisos" },
  "Avisos da Igreja": { pt: "Avisos da Igreja", en: "Church Notices", es: "Avisos de la Iglesia" },

  // Tipo Entrada/Saída
  "Tipo (Entrada/Saída)": { pt: "Tipo (Entrada/Saída)", en: "Type (Income/Expense)", es: "Tipo (Ingreso/Gasto)" },
  "Data (AAAA-MM-DD)": { pt: "Data (AAAA-MM-DD)", en: "Date (YYYY-MM-DD)", es: "Fecha (AAAA-MM-DD)" },

  // Seu navegador
  "Seu navegador não suporta reconhecimento de voz.": { pt: "Seu navegador não suporta reconhecimento de voz.", en: "Your browser doesn't support voice recognition.", es: "Su navegador no soporta reconocimiento de voz." },
  "Permissão de microfone negada.": { pt: "Permissão de microfone negada.", en: "Microphone permission denied.", es: "Permiso de micrófono denegado." },
  "Erro ao iniciar microfone.": { pt: "Erro ao iniciar microfone.", en: "Error starting microphone.", es: "Error al iniciar micrófono." },

  // Devocional
  "Devocional da Manhã": { pt: "Devocional da Manhã", en: "Morning Devotional", es: "Devocional de la Mañana" },
  "Devocional da Tarde": { pt: "Devocional da Tarde", en: "Afternoon Devotional", es: "Devocional de la Tarde" },
  "Devocional da Noite": { pt: "Devocional da Noite", en: "Evening Devotional", es: "Devocional de la Noche" },
  "Manhã": { pt: "Manhã", en: "Morning", es: "Mañana" },
  "Tarde": { pt: "Tarde", en: "Afternoon", es: "Tarde" },
  "Noite": { pt: "Noite", en: "Evening", es: "Noche" },
  "Atualizar": { pt: "Atualizar", en: "Refresh", es: "Actualizar" },
  "Devocional copiado!": { pt: "Devocional copiado!", en: "Devotional copied!", es: "¡Devocional copiado!" },
  "Copiado!": { pt: "Copiado!", en: "Copied!", es: "¡Copiado!" },
  "Copiar": { pt: "Copiar", en: "Copy", es: "Copiar" },
  "Share": { pt: "Compartilhar", en: "Share", es: "Compartir" },

  // Harpa extras
  "Nenhum hino encontrado": { pt: "Nenhum hino encontrado", en: "No hymns found", es: "Ningún himno encontrado" },
  "Uploads da Igreja": { pt: "Uploads da Igreja", en: "Church Uploads", es: "Subidas de la Iglesia" },
  "Por Categoria": { pt: "Por Categoria", en: "By Category", es: "Por Categoría" },
  "Ouvir no YouTube": { pt: "Ouvir no YouTube", en: "Listen on YouTube", es: "Escuchar en YouTube" },
  "Buscar no YouTube": { pt: "Buscar no YouTube", en: "Search on YouTube", es: "Buscar en YouTube" },
  "Letra": { pt: "Letra", en: "Lyrics", es: "Letra" },
  "Detalhes do hino": { pt: "Detalhes do hino", en: "Hymn details", es: "Detalles del himno" },
  "Enviar Hino da Igreja": { pt: "Enviar Hino da Igreja", en: "Upload Church Hymn", es: "Subir Himno de la Iglesia" },
  "Upload de hinos da igreja": { pt: "Upload de hinos da igreja", en: "Church hymn upload", es: "Subida de himnos de la iglesia" },
  "Envie hinos e louvores próprios da sua igreja. Formatos aceitos: MP3, MP4, WAV.": { pt: "Envie hinos e louvores próprios da sua igreja. Formatos aceitos: MP3, MP4, WAV.", en: "Upload hymns and worship songs from your church. Accepted formats: MP3, MP4, WAV.", es: "Suba himnos y alabanzas de su iglesia. Formatos aceptados: MP3, MP4, WAV." },
  "Arraste o arquivo aqui ou clique para selecionar": { pt: "Arraste o arquivo aqui ou clique para selecionar", en: "Drag the file here or click to select", es: "Arrastre el archivo aquí o haga clic para seleccionar" },
  "Em breve disponível": { pt: "Em breve disponível", en: "Coming soon", es: "Próximamente disponible" },
  "* O upload de áudio será habilitado em breve. Você poderá enviar gravações de ensaios, louvores próprios da congregação e muito mais.": { pt: "* O upload de áudio será habilitado em breve. Você poderá enviar gravações de ensaios, louvores próprios da congregação e muito mais.", en: "* Audio upload will be available soon. You'll be able to upload rehearsal recordings, congregation's own worship songs and much more.", es: "* La subida de audio estará disponible pronto. Podrá enviar grabaciones de ensayos, alabanzas propias de la congregación y mucho más." },

  // Assembleia extras

  // Admin Matriz label
  "Admin Matriz": { pt: "Admin Matriz", en: "HQ Admin", es: "Admin Matriz" },

  // Visão geral
  "Visão geral da administração (placeholder)": { pt: "Visão geral da administração", en: "Administration overview", es: "Visión general de la administración" },

  // Finance system
  "Visão Geral": { pt: "Visão Geral", en: "Overview", es: "Visión General" },
  "Lançamentos": { pt: "Lançamentos", en: "Transactions", es: "Movimientos" },
  "Relatórios Contábeis": { pt: "Relatórios Contábeis", en: "Accounting Reports", es: "Informes Contables" },
  "PIX / Dízimos": { pt: "PIX / Dízimos", en: "PIX / Tithes", es: "PIX / Diezmos" },
  "Fluxo Mensal": { pt: "Fluxo Mensal", en: "Monthly Cash Flow", es: "Flujo Mensual" },
  "Distribuição por Categoria": { pt: "Distribuição por Categoria", en: "Distribution by Category", es: "Distribución por Categoría" },
  "Receitas vs Despesas por Categoria": { pt: "Receitas vs Despesas por Categoria", en: "Revenue vs Expenses by Category", es: "Ingresos vs Gastos por Categoría" },
  "Fluxo Acumulado": { pt: "Fluxo Acumulado", en: "Accumulated Flow", es: "Flujo Acumulado" },
  "Saldo Acumulado": { pt: "Saldo Acumulado", en: "Accumulated Balance", es: "Saldo Acumulado" },
  "Receitas": { pt: "Receitas", en: "Revenue", es: "Ingresos" },
  "Despesas": { pt: "Despesas", en: "Expenses", es: "Gastos" },
  "margem": { pt: "margem", en: "margin", es: "margen" },
  "pendentes": { pt: "pendentes", en: "pending", es: "pendientes" },
  "Confirmados": { pt: "Confirmados", en: "Confirmed", es: "Confirmados" },
  "Sem dados": { pt: "Sem dados", en: "No data", es: "Sin datos" },
  "Editar Lançamento": { pt: "Editar Lançamento", en: "Edit Transaction", es: "Editar Movimiento" },
  "Lançamento atualizado!": { pt: "Lançamento atualizado!", en: "Transaction updated!", es: "¡Movimiento actualizado!" },
  "Removido!": { pt: "Removido!", en: "Removed!", es: "¡Eliminado!" },
  "Status atualizado!": { pt: "Status atualizado!", en: "Status updated!", es: "¡Estado actualizado!" },
  "Exportado!": { pt: "Exportado!", en: "Exported!", es: "¡Exportado!" },
  "Demonstrativo de Resultado": { pt: "Demonstrativo de Resultado", en: "Income Statement", es: "Estado de Resultados" },
  "Conta": { pt: "Conta", en: "Account", es: "Cuenta" },
  "RECEITAS": { pt: "RECEITAS", en: "REVENUE", es: "INGRESOS" },
  "DESPESAS": { pt: "DESPESAS", en: "EXPENSES", es: "GASTOS" },
  "RESULTADO DO PERÍODO": { pt: "RESULTADO DO PERÍODO", en: "NET RESULT", es: "RESULTADO DEL PERÍODO" },
  "Balancete": { pt: "Balancete", en: "Trial Balance", es: "Balancete" },
  "Fluxo de Caixa": { pt: "Fluxo de Caixa", en: "Cash Flow", es: "Flujo de Caja" },
  "Saldo Anterior": { pt: "Saldo Anterior", en: "Opening Balance", es: "Saldo Anterior" },
  "(+) Entradas no Período": { pt: "(+) Entradas no Período", en: "(+) Period Income", es: "(+) Ingresos del Período" },
  "(-) Saídas no Período": { pt: "(-) Saídas no Período", en: "(-) Period Expenses", es: "(-) Gastos del Período" },
  "(=) Movimentação Líquida": { pt: "(=) Movimentação Líquida", en: "(=) Net Movement", es: "(=) Movimiento Neto" },
  "SALDO FINAL": { pt: "SALDO FINAL", en: "CLOSING BALANCE", es: "SALDO FINAL" },
  "Total Lançamentos": { pt: "Total Lançamentos", en: "Total Transactions", es: "Total Movimientos" },
  "Fluxo de Caixa Diário": { pt: "Fluxo de Caixa Diário", en: "Daily Cash Flow", es: "Flujo de Caja Diario" },
  "Relatório exportado!": { pt: "Relatório exportado!", en: "Report exported!", es: "¡Informe exportado!" },
  "Erro ao remover": { pt: "Erro ao remover", en: "Error removing", es: "Error al eliminar" },
  "Erro ao atualizar": { pt: "Erro ao atualizar", en: "Error updating", es: "Error al actualizar" },
};


type LanguageContextType = {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType>({
  lang: "pt",
  setLang: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => {
    const saved = localStorage.getItem("app-lang");
    return (saved as Lang) || "pt";
  });

  const changeLang = (l: Lang) => {
    setLang(l);
    localStorage.setItem("app-lang", l);
  };

  const t = (key: string): string => {
    return translations[key]?.[lang] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: changeLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
