-- ============================================================================
-- Ecclesia Chat: chamadas individuais de voz e vídeo
-- Timestamp: 20260803170000
-- ============================================================================
--
-- Separa definitivamente:
--   * ligação individual (voz/vídeo) entre os dois participantes da thread;
--   * reunião em grupo, que permanece um recurso explícito e independente.
--
-- A mídia da ligação individual é WebRTC ponto a ponto. O banco guarda apenas
-- o estado auditável da chamada e sinais efêmeros (offer/answer/ICE). Sinais
-- são apagados assim que a chamada termina; nenhuma mídia passa pelo banco.
-- Todas as mutações são feitas por RPC SECURITY DEFINER com validação dos dois
-- participantes. Não há dependência de Jitsi, Meta ou outro provedor social.
-- ============================================================================

BEGIN;

DO $$
BEGIN
  IF to_regclass('public.internal_threads') IS NULL
     OR to_regclass('public.members') IS NULL THEN
    RAISE EXCEPTION
      'internal_calls_foundation preflight failed: internal_threads/members ausentes';
  END IF;
END;
$$;

-- "meeting" deixa de ser uma thread genérica disfarçada. A origem explícita
-- permite que a interface mostre "Entrar na reunião" somente no fluxo de
-- grupo, nunca nos botões de telefone/câmera de uma conversa individual.
ALTER TABLE public.internal_threads
  DROP CONSTRAINT IF EXISTS internal_threads_source_check;
ALTER TABLE public.internal_threads
  ADD CONSTRAINT internal_threads_source_check CHECK (
    source IN (
      'campaign', 'community', 'group', 'pastoral', 'finance',
      'secretariat', 'prayer', 'general', 'meeting'
    )
  );

CREATE TABLE IF NOT EXISTS public.internal_calls (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  thread_id uuid NOT NULL REFERENCES public.internal_threads(id) ON DELETE CASCADE,
  caller_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  callee_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  mode text NOT NULL,
  status text NOT NULL DEFAULT 'ringing',
  caller_name text NOT NULL,
  caller_avatar_url text,
  callee_name text NOT NULL,
  callee_avatar_url text,
  started_at timestamptz NOT NULL DEFAULT now(),
  answered_at timestamptz,
  ended_at timestamptz,
  end_reason text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT internal_calls_distinct_participants
    CHECK (caller_user_id <> callee_user_id),
  CONSTRAINT internal_calls_mode_check
    CHECK (mode IN ('voice', 'video')),
  CONSTRAINT internal_calls_status_check
    CHECK (status IN (
      'ringing', 'accepted', 'rejected', 'cancelled',
      'ended', 'missed', 'failed'
    ))
);

CREATE INDEX IF NOT EXISTS idx_internal_calls_caller_active
  ON public.internal_calls(caller_user_id, created_at DESC)
  WHERE status IN ('ringing', 'accepted');

CREATE INDEX IF NOT EXISTS idx_internal_calls_callee_active
  ON public.internal_calls(callee_user_id, created_at DESC)
  WHERE status IN ('ringing', 'accepted');

CREATE INDEX IF NOT EXISTS idx_internal_calls_thread_created
  ON public.internal_calls(thread_id, created_at DESC);

DROP TRIGGER IF EXISTS update_internal_calls_updated_at ON public.internal_calls;
CREATE TRIGGER update_internal_calls_updated_at
BEFORE UPDATE ON public.internal_calls
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TABLE IF NOT EXISTS public.internal_call_signals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  call_id uuid NOT NULL REFERENCES public.internal_calls(id) ON DELETE CASCADE,
  sender_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  recipient_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  signal_type text NOT NULL,
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT internal_call_signals_distinct_participants
    CHECK (sender_user_id <> recipient_user_id),
  CONSTRAINT internal_call_signals_type_check
    CHECK (signal_type IN ('offer', 'answer', 'ice')),
  CONSTRAINT internal_call_signals_payload_size
    CHECK (octet_length(payload::text) <= 65536)
);

CREATE INDEX IF NOT EXISTS idx_internal_call_signals_call_created
  ON public.internal_call_signals(call_id, created_at, id);

ALTER TABLE public.internal_calls ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.internal_call_signals ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "internal calls participants select" ON public.internal_calls;
CREATE POLICY "internal calls participants select"
ON public.internal_calls
FOR SELECT TO authenticated
USING (auth.uid() IN (caller_user_id, callee_user_id));

DROP POLICY IF EXISTS "internal call signals participants select" ON public.internal_call_signals;
CREATE POLICY "internal call signals participants select"
ON public.internal_call_signals
FOR SELECT TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.internal_calls c
    WHERE c.id = internal_call_signals.call_id
      AND auth.uid() IN (c.caller_user_id, c.callee_user_id)
  )
);

-- Nenhuma policy de INSERT/UPDATE/DELETE: o cliente só pode mutar pelas RPCs.
REVOKE ALL ON public.internal_calls FROM anon, authenticated;
REVOKE ALL ON public.internal_call_signals FROM anon, authenticated;
GRANT SELECT ON public.internal_calls TO authenticated;
GRANT SELECT ON public.internal_call_signals TO authenticated;

CREATE OR REPLACE FUNCTION public.start_internal_call(
  _thread_id uuid,
  _mode text
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_user_id uuid := auth.uid();
  v_thread public.internal_threads%ROWTYPE;
  v_member_user_id uuid;
  v_callee_user_id uuid;
  v_caller_name text;
  v_caller_avatar text;
  v_callee_name text;
  v_callee_avatar text;
  v_call public.internal_calls%ROWTYPE;
  v_lock_a bigint;
  v_lock_b bigint;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'authentication_required';
  END IF;
  IF _mode NOT IN ('voice', 'video') THEN
    RAISE EXCEPTION 'invalid_call_mode';
  END IF;

  SELECT * INTO v_thread
  FROM public.internal_threads
  WHERE id = _thread_id;

  IF NOT FOUND
     OR v_thread.source <> 'secretariat'
     OR v_thread.member_id IS NULL
     OR NOT public.can_read_internal_thread(v_user_id, _thread_id) THEN
    RAISE EXCEPTION 'direct_thread_not_found_or_forbidden';
  END IF;

  SELECT m.user_id INTO v_member_user_id
  FROM public.members m
  WHERE m.id = v_thread.member_id;

  IF v_member_user_id IS NULL THEN
    RAISE EXCEPTION 'member_has_no_active_user';
  END IF;

  IF v_user_id = v_member_user_id THEN
    v_callee_user_id := COALESCE(v_thread.assigned_to, v_thread.created_by);
  ELSE
    IF NOT public.is_internal_message_staff(v_user_id, v_thread.organization_id) THEN
      RAISE EXCEPTION 'caller_is_not_a_thread_participant';
    END IF;
    v_callee_user_id := v_member_user_id;
  END IF;

  IF v_callee_user_id IS NULL OR v_callee_user_id = v_user_id THEN
    RAISE EXCEPTION 'invalid_call_recipient';
  END IF;

  -- Serializa tentativas dos dois usuários, inclusive chamadas cruzadas.
  v_lock_a := hashtextextended(LEAST(v_user_id::text, v_callee_user_id::text), 731);
  v_lock_b := hashtextextended(GREATEST(v_user_id::text, v_callee_user_id::text), 731);
  PERFORM pg_advisory_xact_lock(v_lock_a);
  PERFORM pg_advisory_xact_lock(v_lock_b);

  -- Se todos os navegadores foram fechados durante o toque, não existe um
  -- cliente para executar o timeout. Expira essas chamadas antes de testar
  -- ocupação, evitando que uma linha antiga bloqueie novas ligações.
  WITH expired AS (
    UPDATE public.internal_calls c
    SET
      status = 'missed',
      ended_at = COALESCE(c.ended_at, now()),
      end_reason = 'ring_timeout_recovered'
    WHERE c.status = 'ringing'
      AND c.started_at <= now() - interval '90 seconds'
      AND (
        v_user_id IN (c.caller_user_id, c.callee_user_id)
        OR v_callee_user_id IN (c.caller_user_id, c.callee_user_id)
      )
    RETURNING c.id
  )
  DELETE FROM public.internal_call_signals s
  WHERE s.call_id IN (SELECT id FROM expired);

  IF EXISTS (
    SELECT 1
    FROM public.internal_calls c
    WHERE c.status IN ('ringing', 'accepted')
      AND (
        v_user_id IN (c.caller_user_id, c.callee_user_id)
        OR v_callee_user_id IN (c.caller_user_id, c.callee_user_id)
      )
  ) THEN
    RAISE EXCEPTION 'participant_already_in_call';
  END IF;

  SELECT
    COALESCE(NULLIF(trim(p.full_name), ''), split_part(u.email, '@', 1), 'Usuário'),
    p.avatar_url
  INTO v_caller_name, v_caller_avatar
  FROM auth.users u
  LEFT JOIN public.profiles p ON p.user_id = u.id
  WHERE u.id = v_user_id;

  SELECT
    COALESCE(NULLIF(trim(p.full_name), ''), split_part(u.email, '@', 1), 'Usuário'),
    p.avatar_url
  INTO v_callee_name, v_callee_avatar
  FROM auth.users u
  LEFT JOIN public.profiles p ON p.user_id = u.id
  WHERE u.id = v_callee_user_id;

  INSERT INTO public.internal_calls (
    organization_id, thread_id, caller_user_id, callee_user_id, mode,
    caller_name, caller_avatar_url, callee_name, callee_avatar_url
  ) VALUES (
    v_thread.organization_id, v_thread.id, v_user_id, v_callee_user_id, _mode,
    COALESCE(v_caller_name, 'Usuário'), v_caller_avatar,
    COALESCE(v_callee_name, 'Usuário'), v_callee_avatar
  )
  RETURNING * INTO v_call;

  RETURN to_jsonb(v_call);
END;
$$;

CREATE OR REPLACE FUNCTION public.transition_internal_call(
  _call_id uuid,
  _action text,
  _reason text DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_user_id uuid := auth.uid();
  v_call public.internal_calls%ROWTYPE;
  v_new_status text;
  v_message text;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'authentication_required';
  END IF;

  SELECT * INTO v_call
  FROM public.internal_calls
  WHERE id = _call_id
  FOR UPDATE;

  IF NOT FOUND OR v_user_id NOT IN (v_call.caller_user_id, v_call.callee_user_id) THEN
    RAISE EXCEPTION 'call_not_found_or_forbidden';
  END IF;

  IF _action = 'accept'
     AND v_call.status = 'ringing'
     AND v_user_id = v_call.callee_user_id THEN
    v_new_status := 'accepted';
  ELSIF _action = 'reject'
     AND v_call.status = 'ringing'
     AND v_user_id = v_call.callee_user_id THEN
    v_new_status := 'rejected';
  ELSIF _action = 'cancel'
     AND v_call.status = 'ringing'
     AND v_user_id = v_call.caller_user_id THEN
    v_new_status := 'cancelled';
  ELSIF _action = 'timeout'
     AND v_call.status = 'ringing'
     AND v_user_id IN (v_call.caller_user_id, v_call.callee_user_id)
     AND v_call.started_at <= now() - interval '30 seconds' THEN
    v_new_status := 'missed';
  ELSIF _action = 'end'
     AND v_call.status = 'accepted' THEN
    v_new_status := 'ended';
  ELSIF _action = 'fail'
     AND v_call.status IN ('ringing', 'accepted') THEN
    v_new_status := 'failed';
  ELSE
    RAISE EXCEPTION 'invalid_call_transition:%->%', v_call.status, _action;
  END IF;

  UPDATE public.internal_calls
  SET
    status = v_new_status,
    answered_at = CASE
      WHEN v_new_status = 'accepted' THEN COALESCE(answered_at, now())
      ELSE answered_at
    END,
    ended_at = CASE
      WHEN v_new_status IN ('rejected', 'cancelled', 'ended', 'missed', 'failed')
        THEN COALESCE(ended_at, now())
      ELSE ended_at
    END,
    end_reason = CASE
      WHEN v_new_status IN ('rejected', 'cancelled', 'ended', 'missed', 'failed')
        THEN left(COALESCE(NULLIF(trim(_reason), ''), v_new_status), 160)
      ELSE end_reason
    END
  WHERE id = _call_id
  RETURNING * INTO v_call;

  IF v_new_status IN ('rejected', 'cancelled', 'ended', 'missed', 'failed') THEN
    DELETE FROM public.internal_call_signals WHERE call_id = _call_id;

    v_message := CASE
      WHEN v_new_status = 'missed' THEN
        CASE WHEN v_call.mode = 'video' THEN 'Videochamada não atendida' ELSE 'Ligação não atendida' END
      WHEN v_new_status = 'rejected' THEN
        CASE WHEN v_call.mode = 'video' THEN 'Videochamada recusada' ELSE 'Ligação recusada' END
      WHEN v_new_status = 'cancelled' THEN
        CASE WHEN v_call.mode = 'video' THEN 'Videochamada cancelada' ELSE 'Ligação cancelada' END
      WHEN v_new_status = 'failed' THEN
        CASE WHEN v_call.mode = 'video' THEN 'Falha na videochamada' ELSE 'Falha na ligação' END
      ELSE
        CASE WHEN v_call.mode = 'video' THEN 'Videochamada encerrada' ELSE 'Ligação encerrada' END
    END;

    INSERT INTO public.internal_messages (
      thread_id, organization_id, sender_user_id, sender_role, body, message_type
    ) VALUES (
      v_call.thread_id, v_call.organization_id, v_user_id, 'participant', v_message, 'system'
    );
  END IF;

  RETURN to_jsonb(v_call);
END;
$$;

CREATE OR REPLACE FUNCTION public.send_internal_call_signal(
  _call_id uuid,
  _signal_type text,
  _payload jsonb
) RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_user_id uuid := auth.uid();
  v_call public.internal_calls%ROWTYPE;
  v_recipient uuid;
  v_signal_id bigint;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'authentication_required';
  END IF;
  IF _signal_type NOT IN ('offer', 'answer', 'ice')
     OR _payload IS NULL
     OR octet_length(_payload::text) > 65536 THEN
    RAISE EXCEPTION 'invalid_call_signal';
  END IF;

  SELECT * INTO v_call
  FROM public.internal_calls
  WHERE id = _call_id;

  IF NOT FOUND
     OR v_call.status NOT IN ('ringing', 'accepted')
     OR v_user_id NOT IN (v_call.caller_user_id, v_call.callee_user_id) THEN
    RAISE EXCEPTION 'call_not_active_or_forbidden';
  END IF;

  v_recipient := CASE
    WHEN v_user_id = v_call.caller_user_id THEN v_call.callee_user_id
    ELSE v_call.caller_user_id
  END;

  INSERT INTO public.internal_call_signals (
    call_id, sender_user_id, recipient_user_id, signal_type, payload
  ) VALUES (
    _call_id, v_user_id, v_recipient, _signal_type, _payload
  )
  RETURNING id INTO v_signal_id;

  RETURN v_signal_id;
END;
$$;

REVOKE ALL ON FUNCTION public.start_internal_call(uuid, text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.transition_internal_call(uuid, text, text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.send_internal_call_signal(uuid, text, jsonb) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.start_internal_call(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.transition_internal_call(uuid, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.send_internal_call_signal(uuid, text, jsonb) TO authenticated;

ALTER TABLE public.internal_calls REPLICA IDENTITY FULL;
ALTER TABLE public.internal_call_signals REPLICA IDENTITY FULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'internal_calls'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.internal_calls;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'internal_call_signals'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.internal_call_signals;
  END IF;
END;
$$;

DO $$
BEGIN
  IF to_regclass('public.internal_calls') IS NULL
     OR to_regclass('public.internal_call_signals') IS NULL
     OR to_regprocedure('public.start_internal_call(uuid,text)') IS NULL
     OR to_regprocedure('public.transition_internal_call(uuid,text,text)') IS NULL
     OR to_regprocedure('public.send_internal_call_signal(uuid,text,jsonb)') IS NULL THEN
    RAISE EXCEPTION 'internal_calls_foundation verification failed';
  END IF;
  RAISE NOTICE 'internal_calls_foundation: chamadas individuais e sinalização segura confirmadas ✓';
END;
$$;

COMMIT;
