// This file is automatically generated. Do not edit it directly.
//
// EXCEÇÃO DELIBERADA (separação de ambientes): a URL/chave do Supabase são
// lidas de `environment` (src/config/environment.ts) em vez de
// `import.meta.env` direto. Importar `environment` já valida e falha fechado
// ANTES desta linha se produção/staging estiverem misturados — por isso a
// validação acontece antes de `createClient`, nunca depois.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { environment } from '@/config/environment';

const SUPABASE_URL = environment.supabaseUrl;
const SUPABASE_PUBLISHABLE_KEY = environment.supabasePublishableKey;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});